services:
  # React Frontend
  frontend:
    image: node:latest
    working_dir: /usr/src/app
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm run dev"]
    depends_on:
      - backend
  # Node.js + Express Backend
  backend:
    image: node:latest
    working_dir: /usr/src/app
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    command: ["sh", "-c", "npm install && npx prisma migrate deploy && npm run dev"]
    env_file:
      - .env

volumes:
  postgres_data:
